name = "KnetNLPModelsProblems"
uuid = "bc935da4-1950-4bc0-b8ba-f68a9e81f524"
authors = ["farhadrclass <31899325+farhadrclass@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSOSolvers = "10dff2fc-5484-5881-a0e0-c90441020f8a"
Knet = "1902f260-5fb4-5aff-8c31-6271790ab950"
KnetNLPModels = "9601d21a-7b1e-4fc7-9dab-5c3f545997d5"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MarketTechnicals = "4f8c86c6-9e40-5506-9807-98571cb48bc8"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SolverParameters = "d076d87d-d1f9-4ea3-a44b-64b4cdd1e470"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StochasticRounding = "3843c9a1-1f18-49ff-9d99-1b4c8a8e97ed"

[compat]
JSOSolvers = "0.10"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
